name: Require Decal Run Comment

on:
  issue_comment:
    types: [created]

jobs:
  Reqiure-decal-run-comment:
    name: Require Decal Run Comment
    runs-on: ubuntu-latest
    steps:
      - name: Check if triggering comment contains "decal run"
        id: check-comment
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const body = context.payload.comment.body
            return body === 'decal run'

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Trigger Decal Run Workflow
        if: ${{ steps.check-comment.outputs.result }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo triggering decal!

      - name: Get PR SHA
        id: pr-sha
        env:
          ISSUE: ${{ github.event.issue.number }}
          FULL_NAME: ${{ github.event.repository.full_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "pr-sha=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$FULL_NAME/pulls/$ISSUE | jq -r '.head.sha')" >> $GITHUB_OUTPUT

      - name: Give commit status to current head PR
        if: ${{ steps.check-comment.outputs.result }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_SHA: ${{ steps.pr-sha.outputs.pr-sha }}
          FULL_NAME: ${{ github.event.repository.full_name }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$FULL_NAME/statuses/$PR_SHA \
            -f "state=success" -f "description=Ran decal for latest commit" \
            -f "context=decal-run-ci"
