name: Require Decal Run Comment

on:
  issue_comment:
    types: [created]

jobs:
  Reqiure-decal-run-comment:
    name: Require Decal Run Comment
    runs-on: ubuntu-latest
    steps:
      - name: Check if triggering comment contains "decal run"
        id: check-comment
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            console.log(context)
            const body = context.payload.comment.body
            return body === 'decal run'

      - name: Get PR SHA
        id: pr-sha
        env:
          ISSUE: ${{ github.issue.number }}
          FULL_NAME: ${{ github.payload.repository.full_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$FULL_NAME/pulls/$ISSUE

      - name: Trigger Decal Run Workflow
        if: ${{ steps.check-comment.outputs.result }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo triggering decal!
          echo $CHECK
