name: Decal Guide Comment

on:
  pull_request:

jobs:
  guide:
    name: Guide decal trigger
    runs-on: ubuntu-latest
    steps:
      - name: Run if deploy to decisionsvc
        id: determine
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            // assumes this action runs on pull request event.
            const prBody = context.payload.pull_request.body
            const header = "## Service To Deploy"

            // extracts the content of "Service To Deploy" section.
            let svcs = prBody.substring(prBody.indexOf(header) + header.length)
            svcs = svcs.substring(0, svcs.indexOf("## ")).trim()
            return svcs.indexOf("decisionsvc") >= 0

      - name: Checkout Main branch
        # This is necessary to use ./.github/workflows/decal-find.js
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Check changed files
        id: run_decal
        uses: actions/github-script@v7
        env:
          DETERMINE: ${{ steps.determine.outputs.result }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const { DETERMINE } = process.env
            if (DETERMINE === 'true') {
              return 'true'
            }
            const script = require('./.github/workflows/decal-find.js')
            return await script({github, context});

      - name: Fill required comment template with parameters
        if: ${{ steps.run_decal.outputs.result == 'true' }}
        id: template-required
        uses: chuhlomin/render-template@v1.8
        with:
          template: .github/workflows/decal-guide-comment-required-run.md
          vars: |
            prnum: ${{ github.event.pull_request.number }}

      - name: Fill not required comment template with parameters
        if: ${{ steps.run_decal.outputs.result == 'false' }}
        id: template-not-required
        uses: chuhlomin/render-template@v1.8
        with:
          template: .github/workflows/decal-guide-comment-not-required-run.md
          vars: |
            prnum: ${{ github.event.pull_request.number }}

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: If you want to run decal manually to identify the impact of your PR

      - name: Create or update required comment
        if: ${{ steps.run_decal.outputs.result == 'true' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.template-required.outputs.result }}
          edit-mode: replace

      - name: Create or update not-required comment
        if: ${{ steps.run_decal.outputs.result == 'false' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.template-not-required.outputs.result }}
          edit-mode: replace

      - name: Give commit status check if not-required to run decal
       if: ${{ steps.run_decal.outputs.result == 'false' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FULL_NAME: ${{ github.event.repository.full_name }}
          SHA: ${{ github.sha }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$FULL_NAME/statuses/$SHA \
            -f "state=success" -f "description=Not required to run decal => auto success" \
            -f "context=decal-run-ci"
