name: Require Run Comment

on:
  issue_comment:
    types: [created]

jobs:
  comment-run-initialization:
    name: run initialization
    runs-on: ubuntu-latest
    steps:
      - name: check pr
        run: |
          echo ${{ github.event.issue.number }}
      - name: Checkout main branch
        # This is necessary to checkout ./.github/workflows/decal-find.js
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Check changed files
        id: run-comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const script = require('./.github/workflows/changes-find.js')
            return (await script({github, context}));
      - name: Read output
        run: |
          echo ${{ steps.run-comment.outputs.result }}
